### ISSUE TITLE
请问这个能否提供一个只添加别名的选项

### ISSUE THREAD

**Issue by Chenm4** [terwer/siyuan-plugin-custom-slug#11]
我希望这个能否值添加别名不添加命名，因为如果添加了命名例如文档名为象棋，命名为chess-hash，那么我用[[象棋  引用这个文档只能显示出来chess-hash，缺点就是第一个它是英文翻译过来的不准确，第二点就是它后面还有hash比较难看，感觉可以提供一个选项全部用别名？因为别名也可以用[[搜索到，
![image](https://github.com/terwer/siyuan-plugin-custom-slug/assets/98648589/52f66332-90eb-4487-9232-4fca0577e9a9)
![image](https://github.com/terwer/siyuan-plugin-custom-slug/assets/98648589/70453d59-9d7f-48b3-abcb-7697ac6cfc93)

**Comment by terwer** [comment]
目前是有两个属性存储这个值的，一个是custom-slug(自定义字段)，一个是name(命名)，如果name不需要，可以提供选项关闭。

**Comment by Chenm4** [comment]
好的，感谢！

**Comment by terwer** [comment]
https://github.com/terwer/siyuan-plugin-custom-slug/pull/38

已提供配置，升级 0.2.0

![image](https://github.com/terwer/siyuan-plugin-custom-slug/assets/3259282/2d02e4ce-2de1-4303-906d-3a9415a52473)
