### ISSUE TITLE
不能生成别名

### ISSUE THREAD

**Issue by itachaaa** [terwer/siyuan-plugin-custom-slug#122]
现象如下：
版本：2.10.6

![图片](https://github.com/terwer/siyuan-plugin-custom-slug/assets/31896600/d067efc7-2045-48b6-aac3-19e77079f5d6)

![图片](https://github.com/terwer/siyuan-plugin-custom-slug/assets/31896600/83f08575-6938-4356-8541-411f0f888047)

**Comment by zhangjunquan** [comment]
我这里也没生成成功

![image](https://github.com/terwer/siyuan-plugin-custom-slug/assets/9114193/c8c3c1cc-3fdf-4d89-ad93-c2ceb8f7084e)

**Comment by terwer** [comment]
域名被墙了。暂时开启全局代理才能使用。

**Comment by terwer** [comment]
域名解析已恢复
