### ISSUE TITLE
文档自动命名功能与双链无法配合

### ISSUE THREAD

**Issue by DionathanJoestar** [terwer/siyuan-plugin-custom-slug#36]
在创建双链的时候，会自动用生成的命名来代替原本的文档标题，导致生成的双链需要手动调整。能否增加一个功能，关闭自动命名功能，只保留别名。自动生成的名字在双链中无论如何都看不懂吧，反而是有了别名就可以简单的在创建双链的时候达到分辨的效果。
![image](https://github.com/terwer/siyuan-plugin-custom-slug/assets/133741096/f58ee7f3-390f-48c1-9ce5-ed06286ed001)

**Comment by terwer** [comment]
已提供配置
![image](https://github.com/terwer/siyuan-plugin-custom-slug/assets/3259282/d5404076-db65-4975-a02e-9f2c8edfefa6)
