### ISSUE TITLE
一些提升建议

### ISSUE THREAD

**Issue by IAliceBobI** [terwer/siyuan-plugin-custom-slug#6]
## 更进一步
或者支持处理全部的文档。

保存一下插件数据，比如处理的文档里面最大的 updated值。

下次就不用全部文件都处理，只需要处理，比上次保存的updated值大的文件。

**Comment by terwer** [comment]
已支持。第一次全量，后续增量

右键菜单

![image](https://github.com/terwer/siyuan-plugin-custom-slug/assets/3259282/82bde9e1-5c7e-4736-acf4-d76d82b28979)

![70b6840d4e5cfe0bf3aaaa1f8127e9ed](https://github.com/terwer/siyuan-plugin-custom-slug/assets/3259282/d08c310b-e752-4923-8158-cbfbad7b5ff7)


批量状态
![image](https://github.com/terwer/siyuan-plugin-custom-slug/assets/3259282/4a8b2a42-dd09-4a66-871a-43ada86f0089)

**Comment by terwer** [comment]
请更新 0.3.0
